version: '3.7'
services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb-instance
    environment:
      - ARANGO_ROOT_PASSWORD=arangodb
    ports:
      - "8529:8529"
    volumes:
      - ./arangodb-data:/var/lib/arangodb3
      - ./arangodb-apps-data:/var/lib/arangodb3-apps
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
