version: '3.7'
services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb-instance
    environment:
      - ARANGO_ROOT_PASSWORD=arangodb
    ports:
      - "8529:8529"
    volumes:
      - ./arangodb-data:/var/lib/arangodb3
      - ./arangodb-apps-data:/var/lib/arangodb3-apps
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  redis:
    image: redis:latest
    depends_on:
      - arangodb
    container_name: redis-instance
    restart: always
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
